//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Claw"",
            ""id"": ""b79ea7b9-a4b2-4f30-bd6c-ced9916f8610"",
            ""actions"": [
                {
                    ""name"": ""MoveClaw"",
                    ""type"": ""Value"",
                    ""id"": ""08019696-22b4-4311-8c9f-54df1bb2a42d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""946e1c4e-ed5a-4c12-9b31-4057356e897f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""7a653d7e-c22a-4312-bf3b-be3ee82ce3fa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a066d22f-d204-48c3-8051-c87f63d296e5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d79a7a18-3c7f-449f-8712-f4432a1a8e17"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a714acc8-0ed6-4f7c-9eaa-07167c31c520"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8bd9e0d4-400d-4fcb-9e7f-ba9bc22571df"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Claw
        m_Claw = asset.FindActionMap("Claw", throwIfNotFound: true);
        m_Claw_MoveClaw = m_Claw.FindAction("MoveClaw", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Claw
    private readonly InputActionMap m_Claw;
    private List<IClawActions> m_ClawActionsCallbackInterfaces = new List<IClawActions>();
    private readonly InputAction m_Claw_MoveClaw;
    public struct ClawActions
    {
        private @PlayerInputs m_Wrapper;
        public ClawActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveClaw => m_Wrapper.m_Claw_MoveClaw;
        public InputActionMap Get() { return m_Wrapper.m_Claw; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ClawActions set) { return set.Get(); }
        public void AddCallbacks(IClawActions instance)
        {
            if (instance == null || m_Wrapper.m_ClawActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ClawActionsCallbackInterfaces.Add(instance);
            @MoveClaw.started += instance.OnMoveClaw;
            @MoveClaw.performed += instance.OnMoveClaw;
            @MoveClaw.canceled += instance.OnMoveClaw;
        }

        private void UnregisterCallbacks(IClawActions instance)
        {
            @MoveClaw.started -= instance.OnMoveClaw;
            @MoveClaw.performed -= instance.OnMoveClaw;
            @MoveClaw.canceled -= instance.OnMoveClaw;
        }

        public void RemoveCallbacks(IClawActions instance)
        {
            if (m_Wrapper.m_ClawActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IClawActions instance)
        {
            foreach (var item in m_Wrapper.m_ClawActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ClawActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ClawActions @Claw => new ClawActions(this);
    public interface IClawActions
    {
        void OnMoveClaw(InputAction.CallbackContext context);
    }
}
